### ISSUE TITLE
not working with P2D

### ISSUE THREAD

**Issue by matheplica** [micycle1/PGS#39]
When I used with P2D mode. I've got always a NullPointerException that block the script.

**Comment by micycle1** [comment]
Could you provide the code you're running and the stack trace of the error?

There is one known limitation with the P2D renderer, which causes an error like this:

`java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 37 out of bounds for float[2]`

This occurs because P2D actually uses `PShapeOpenGL` for PShapes, rather than `PShape` (the kind that PGS creates). This exception only effects shapes whose _family_ is `GEOMETRY`  (such as POINTS, etc.).

---

The code currently returns a `GEOMETRY` PShape when the shape to convert from is _null_. This will be amended for the next version, 1.2.0.

**Comment by micycle1** [comment]
In 1.2.0, output PShapes are now always created with a shape family of PATH (rather than GEOMETRY) to maximise compatibility with the P2D renderer.
