### ISSUE TITLE
Examples using the 'Illustrations'

### ISSUE THREAD

**Issue by robottini** [micycle1/PGS#44]
Hi, in the 'Illustrations' part in the README.MD file there are many examples. I think this examples are obtained using the library. Why not expand the examples  library  with the code used to get the images shown? I think this could be very useful for the people approaching the library,

**Comment by micycle1** [comment]
Hello Alessandro, I'm sorry I haven't addressed this until now.

It's true that it could be _useful_, but I think it's possibly overkill, since (I'd hope) the methods that the gifs illustrate should be very easy to both locate in the codebase use.

Are there any particular methods you were having trouble with?

**Comment by micycle1** [comment]
Stale.
